src/Entity/Article.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Article
 *
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ORM\Table(name="article")
 */
class Article
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", nullable=true)
     *
     */
    private $title;


    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     *
     */
    private $createdDate;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     *
     */
    private $description;

    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="App\Entity\Tag", mappedBy="articles")
     */
    private $tags;


    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param string $description
     * @return Article
     */
    public function setDescription($description)
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $title
     * @return Article
     */
    public function setTitle(string $title): Article
    {
        $this->title = $title;
        return $this;
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * @return ArrayCollection|Tag[]
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * @return string
     */
    public function getTagsNameInString()
    {
        $tagsName = [];
        foreach ($this->tags as $tag){
            $tagsName[] = $tag->getName();
        }
        return implode(', ', $tagsName);
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
            $tag->addArticle($this);
        }
        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
            $tag->removeArticle($this);
        }
        return $this;
    }

    /**
     * @param \DateTime $createdDate
     * @return Article
     */
    public function setCreatedDate(\DateTime $createdDate): Article
    {
        $this->createdDate = $createdDate;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedDate(): \DateTime
    {
        return $this->createdDate;
    }

}

templates/add_article.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <link rel="stylesheet" href="{{ asset('dist/fastselect.min.css') }}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{{ asset('dist/fastselect.standalone.js') }}"></script>
    {% for flashMessage in app.session.flashbag.get('error') %}
        <div class="flashbag"
             style="text-align: center; margin-top: 50px; width: 50%; font-size: 20px; border: solid 2px red">{{ flashMessage }}</div>
    {% endfor %}
    <div class="row">
        <div class="col" style="width: 40%; margin-top: 50px">
            <h2>Добавление новой статьи</h2>
            {{ form(form) }}
        </div>
        <div class="col">
            {{ render(controller('App\\Controller\\BaseController::showTags')) }}
        </div>
    </div>
    <style>
        .ui-datepicker-trigger {
            width: 30px;
        }

        #app_bundle_article_type_createdDate {
            width: 200px;
            display: inline-block;
            margin-right: 5px;
        }

        #app_bundle_article_type_description {
            min-height: 400px;
        }
    </style>
{% endblock %}
{% block javascripts %}
    <script>
        $(function () {
            $("#app_bundle_article_type_createdDate").datepicker({
                dateFormat: "d/MM/yy",
                showOn: "button",
                buttonImage: "{{ asset('calendar-alt-regular.svg') }}",
                buttonImageOnly: true,
                buttonText: "Выберите дату",
            });
        });
        $('.tagsInput').fastselect();
    </script>
{% endblock %}

templates/article.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
        <div class="col" style="width: 40%; margin-top: 10px">
            <div style="padding: 10px; word-wrap:break-word;">
                <h2>{{ article.title }}</h2>
                <p>
                    <span>{{ article.createdDate.format('d M Y') }} / </span>
                    <span>{{ article.tagsNameInString }}</span>
                </p>
                <p>{{ article.description }}</p>
            </div>
            <hr style="border: 1px solid black">
        </div>
        <div class="col">
            {{ render(controller('App\\Controller\\BaseController::showTags')) }}
        </div>
    </div>
{% endblock %}

templates/articles_by_tag.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
        <div class="col" style="width: 40%; margin-top: 10px">
            <h1>Статьи по тегу "{{ tagName }}"</h1>
            {% for article in articles %}
                <div style="padding: 10px; word-wrap:break-word;">
                    <h2>{{ article.title }}</h2>
                    <p>
                        <span>{{ article.createdDate.format('d M Y') }} / </span>
                        <span>{{ article.tagsNameInString }}</span>
                    </p>
                    <p>{{ article.description | truncate(500) }}</p>
                    <p style="float: right;"><a href="{{ path('app_show_article_details', {id: article.id}) }}">читать далее...</a></p>
                </div>
                <hr style="border: 1px solid black; margin-top: 30px">
            {% endfor %}
        </div>
        <div class="col">
            {{ render(controller('App\\Controller\\BaseController::showTags')) }}
        </div>
    </div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    {% block stylesheets %}
    {% endblock %}
</head>
<body>
<div class="container">
    {{ include('header.html.twig') }}
    {% block body %}{% endblock %}
    {% block javascripts %}{% endblock %}
</div>
</body>
</html>

templates/header.html.twig
<div class="header" style="border-bottom: 3px #868686 solid; -webkit-box-shadow: 0px 15px 16px -1px rgba(0,0,0,0.75);
-moz-box-shadow: 0px 15px 16px -1px rgba(0,0,0,0.75);
box-shadow: 0px 15px 16px -1px rgba(0,0,0,0.75);">
    <a style="margin-left: 10px" href="{{ path('homepage') }}"><span><img src="{{ asset('Logo/logo.png') }}" style="width: 75px"></span></a>
    <span style="float: right; margin-top: 20px; padding-right: 10px">
        <a class="btn btn-primary" href="{{ path('homepage') }}">Главная</a>
        <a class="btn btn-primary" href="{{ path('app_add_article') }}">Добавить статью</a>
    </span>
</div>

templates/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="row">
        <div class="col" style="width: 40%; margin-top: 10px">
            <h1>Блог</h1>
            {% for article in articles %}
                <div style="padding: 10px; word-wrap:break-word;">
                    <h2>{{ article.title }}</h2>
                    <p>
                        <span>{{ article.createdDate.format('d M Y') }} / </span>
                        <span>{{ article.tagsNameInString }}</span>
                    </p>
                    <p>{{ article.description | truncate(500)}}</p>
                    <p style="float: right;"><a href="{{ path('app_show_article_details', {id: article.id}) }}">читать далее...</a></p>
                </div>
                <hr style="border: 1px solid black; margin-top: 30px">
                {% else %}
                <h2>К сожалению, не написано ни одной статьи... <a href="{{ path('app_add_article') }}"> Добавить?</a></h2>
            {% endfor %}
        </div>
        <div class="col">
            {{ render(controller('App\\Controller\\BaseController::showTags')) }}
        </div>
    </div>
{% endblock %}

templates/tags.html.twig
<script src="{{ asset('tagcanvas.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('jquery.tagcanvas.min.js') }}" type="text/javascript"></script>
<div class="tags-wrapper" style="float: right; padding-top: 10px; text-align: center;">
    <h1 style="margin-bottom: 20px">Тэги</h1>
    <div style="padding: 20px;
            background-image: url({{ asset('Logo/1307521026_Vector_Clipart_photo-resizer.ru.png') }}); background-position: center; background-repeat: no-repeat;">
        <div id="myCanvasContainer">
            <canvas width="500" height="350" id="myCanvas">
                <ul>
                    {% for tag in tags %}
                        <li><a href="{{ path('app_show_articles_by_tag', {id: tag.id}) }}">{{ tag.name }}</a></li>
                    {% else %}
                        <li>Нет тегов</li>
                    {% endfor %}
                </ul>
            </canvas>
        </div>
    </div>
</div>
<script type="text/javascript">
    var options = {
        textColour: 'black',
        textHeight: 20,
        outlineMethod: "block",
        depth: 0.9,
        minSpeed: 0.1,
        maxSpeed: 0.05,
        initial: [0.3, -0.1],
        outlineColour: "#587DFF",
        clickToFront: 750,
        bgOutline: false,
        freezeDecel: true,
        wheelZoom: false
    };
    window.onload = function () {
        try {
            TagCanvas.Start('myCanvas', '', options);
        } catch (e) {
            document.getElementById('myCanvasContainer').style.display = 'none';
        }
    };
</script>